FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# COVID


Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/overview]

### Overview [GET]

+ Response 200 (application/json)
        {
            "activeCases": 12,
            "sumDeaths": 12,
            "sumCases": 12,
            "sumCured": 10
        }

## Questions Collection [/daily/hospital?area=[1,2,3]]

### List hospitalizations [GET]

+ Response 200 (application/json)
        {
            "items": [
                {
                    "areaId": 10,
                    "areaName": "Austria",
                    "data": [
                        {
                            "date": "01.02.2020",
                            "values": [
                                {
                                    "identifier": "intenseBeds",
                                    "value": 12
                                },
                                {
                                    "identifier": "normalBeds",
                                    "value": 15
                                }
                            ]
                        }
                    ]
                }
            ]
        }
        

## Questions Collection [/daily/new-cases?area=[1,2,3]&relative=true]


### List new cases [GET]

+ Response 200 (application/json)
        {
            "items": [
                {
                    "areaId": 10,
                    "areaName": "Austria",
                    "data": [
                        {
                            "date": "01.02.2020",
                            "values": [
                                {
                                    "identifier": "newCases",
                                    "value": 120
                                }
                            ]
                        }
                    ]
                }
            ]
        }
        

## Questions Collection [/daily/deaths?area=[1,2,3]&relative=true]


### List new cases [GET]

+ Response 200 (application/json)
        {
            "items": [
                {
                    "areaId": 10,
                    "areaName": "Austria",
                    "data": [
                        {
                            "date": "01.02.2020",
                            "values": [
                                {
                                    "identifier": "deaths",
                                    "value": 120
                                }
                            ]
                        }
                    ]
                }
            ]
        }
       

## Questions Collection [/daily/tests?area=[1,2,3]&relative=true]


### List tests [GET]

+ Response 200 (application/json)
        {
            "items": [
                {
                    "areaId": 10,
                    "areaName": "Austria",
                    "data": [
                        {
                            "date": "01.02.2020",
                            "values": [
                                {
                                    "identifier": "tests",
                                    "value": 120
                                }
                            ]
                        }
                    ]
                }
            ]
        }
        

## Questions Collection [/daily/cases?area=[1,2,3]]


### List cases [GET]

+ Response 200 (application/json)
        {
            "items": [
                {
                    "areaId": 10,
                    "areaName": "Austria",
                    "data": [
                        {
                            "date": "01.02.2020",
                            "values": [
                                {
                                    "identifier": "activeCases",
                                    "value": 120
                                },
                                {
                                    "identifier": "newCases",
                                    "value": 120
                                },
                                {
                                    "identifier": "cured",
                                    "value": 120
                                },
                                {
                                    "identifier": "deaths",
                                    "value": 120
                                },
                                {
                                    "identifier": "tests"
                                    "value": 120
                                },
                                {
                                    "identifier": "intenseBeds"
                                    "value": 120
                                },
                                {
                                    "identifier": "normalBeds"
                                    "value": 120
                                }
                            ]
                        }
                    ]
                }
            ]
        }
        

## Questions Collection [/area-info?area=[1,2,3]&relative=true]


### List new cases [GET]

+ Response 200 (application/json)
        {
            "items": [
                {
                    "areaId": 11,
                    "areaName": "Villach-Stadt",
                    "data": [
                        {
                            "identifier": "activeCases",
                            "value": 120
                        },
                        {
                            "identifier": "sumCases",
                            "value": 120
                        },
                        {
                            "identifier": "sumCured",
                            "value": 120
                        },
                        {
                            "identifier": "sumDeaths",
                            "value": 120
                        }
                    ]
                }
            ]
        }
        

## Questions Collection [/distribution/sex?area=[1,2,3]]


### List new cases [GET]

+ Response 200 (application/json)
        {
            "items": [
                {
                    "areaId": 10,
                    "areaName": "Austria",
                    "data": [
			{
			    "sex": "male",
			    "values": [
  	                  	{
        	                    "identifier": "cured",
        	               	    "value": 120
        	                },
        	                {
                	            "identifier": "dead",
                        	    "value": 120
	                        }
			    ]
			    "sex": "female",
			    "values": [
  	                  	{
        	                    "identifier": "cured",
        	               	    "value": 120
        	                },
        	                {
                	            "identifier": "dead",
                        	    "value": 120
	                        }
			    ]
			}
                    ]
                }
            ]
        }
        

## Questions Collection [/provinces]


### List regions [GET]

+ Response 200 (application/json)
        {
            "items": [
                {
                    "areaId": 1,
                    "areaName": "Burgenland"
                },
                {
                    "areaId": 10,
                    "areaName": "Austria"
                }
            ]
        }
        

## Questions Collection [/districts]


### List districts [GET]

+ Response 200 (application/json)
        {
            "items": [
                {
                    "areaId": 11,
                    "areaName": "Villach-Stadt"
                }
            ]
        }
        

## Questions Collection [/distribution/age-sex/cases?area=[1,2,3]]


### Age-Sex Comparison [GET]

+ Response 200 (application/json)
        {
            "items": [
                {
                  "areaId": "1",
                  "areaName": "Burgenland",
                  "data": [
                       {
                            "ageIntervalId": 1,
                            "ageInterval": "< 5",
                            "values": [
                                {
                                     "identifier": "maleCases",
                                     "value": 123
                                },
                                {
                                     "identifier": "femaleCases",
                                     "value": 234
                                }
                            ]
                        }
                    ]
                }
            ]
        }

## Questions Collection [/distribution/age-sex/deaths?area=[1,2,3]]


### Age-Sex Comparison [GET]

+ Response 200 (application/json)
        {
            "items": [
                {
                  "areaId": "1",
                  "areaName": "Burgenland",
                  "data": [
                       {
                            "ageIntervalId": 1,
                            "ageInterval": "< 5",
                            "values": [
                                {
                                     "identifier": "maleDeaths",
                                     "value": 2
                                },
                                {
                                     "identifier": "femaleDeaths",
                                     "value": 1
                                }
                            ]
                        }
                    ]
                }
            ]
        }        
        
        

## Comparison [/hospital-bed-utilizations?area=[1,2,3]&type=0]


### List tests [GET]

+ Response 200 (application/json)
        {
            "items": [
                {
                    "areaId": 10,
                    "areaName": "Austria",
                    "data": [
                        {
                            "date": "01.02.2020",
                            "values": [
                                {
                                    "identifier": "availableBeds",
                                    "value": 120
                                },
                                {
                                    "identifier": "utilizedBeds",
                                    "value": 80
                                }
                            ]
                        }
                    ]
                }
            ]
        }        

## Comparison [/daily/generalSituation?area=[1,2,3]]

### List tests [GET]

+ Response 200 (application/json)
        {
            "items": [
                {
                    "areaId": 10,
                    "areaName": "Austria",
                    "data": [
                        {
                            "date": "01.02.2020",
                            "values": [
                                {
                                    "identifier": "deaths",
                                    "value": 120
                                },
                                {
                                    "identifier": "newCases",
                                    "value": 120
                                },
                                {
                                    "identifier": "hospitalizations",
                                    "value": 120
                                },
                                {
                                    "identifier": "casesDifference",
                                    "value": 10
                                }
                            ]
                        }
                    ]
                }
            ]
        }
